--[[

	bWhitelist Chinese Simplified

	Contributors:

	8Z - STEAM_1:0:33380074

]]

bWhitelist.Language = {
	permission_failure = "你没有权限这么做。",
	disabled_whitelist = "这个职业的白名单被禁用了。",
	no_whitelist_permission = "你没有权限修改这个白名单。",
	search_jobs = "搜索职业...",
	steamid_finder = "SteamID查找器",
	type = "类型",
	value = "值",
	team_name = "名字",
	select_job = "在左侧选择职业...",
	enable_whitelist = "启用白名单？",
	enabling_whitelist = "白名单启用中...",
	add_to_whitelist = "加入白名单",
	disable_whitelist = "禁用白名单",
	clear_whitelist = "清除白名单",
	search = "搜索...",
	no_data = "无数据！",
	retrieving = "获取中...",
	admin_mode = "管理模式",
	admin_tab = "管理员",
	jobs_tab = "职业",
	players_tab = "玩家",
	default_team = "这是默认职业。你不能给默认职业添加白名单",
	remove_from_whitelist = "从白名单中移除",
	player_name = "名字",
	remove_from_whitelist_selected_tooltip = "将选中用户从一个白名单中去除",
	add_to_whitelist_selected_tooltip = "将选中用户加入一个白名单。",
	clear_whitelist_tooltip = "[管理专用] 清除白名单。所有用户和用户组将被删除。",
	disable_whitelist_tooltip = "去除白名单。任何人都能选择这个职业。",
	add_to_whitelist_tooltip = "将一个SteamID，SteamID64或用户组加入白名单。",
	remove_from_whitelist_tooltip = "将一个SteamID，SteamID64或用户组加入从一个白名单中去除",
	in_jobs_file_tooltip = "你不能禁用这个白名单，因为它在你的DarkRP职业文件中启用了bWhitelist。",
	add_steamid = "添加SteamID/64",
	add_usergroup = "添加Usergroup",
	add_usergroup_modal = "输入你想添加的用户组。",
	add_steamid_modal = "在下面黏贴你想添加的SteamID/SteamID64。\n不要忘记有一个更简单的方法：使用菜单中的\"Player\"栏目！",
	error = "Error",
	not_a_steamid_or_64 = "那不是一个SteamID或SteamID64！",
	already_exists = "那已经在白名单中存在了！",
	doesnt_exist = "那在白名单中不存在！",
	copy = "复制",
	copy_tooltip = "复制选中的用户组或SteamID.",
	player_left = "抱歉，那个玩家似乎退出了服务器。",
	no_enabled_whitelists = "你没有权限使用任何一个白名单！",
	import_from_mayoz = "从Mayoz's Whitelisting System导入白名单",
	import_from_nordahl = "从Nordahl's Whitelisting System导入白名单",
	import_from_old_bwhitelist = "从旧版本的bWhitelist导入白名单",
	view = "查看",
	no_import = "无法找到导入数据，或数据受到了损坏无法导入。",
	import_from_old_bwhitelist_tooltip = "如果我们能找到旧版本的bWhitelist白名单数据，我们将试图将其导入到新版本中。",
	import_from_mayoz_tooltip = "如果我们能找到Mayoz's Whitelisting System的白名单数据，我们将试图将其导入到bWhitelist中。",
	import_from_nordahl_tooltip = "如果我们能找到Nordahl's Whitelisting System的白名单数据，我们将试图将其导入到bWhitelist中。",
	disable_all_whitelists = "所有职业的白名单都会被禁用。所有数据都会保留。",
	enable_all_whitelists = "所有职业的白名单都会被启用。",
	steamprofile = "Steam个人主页",
	confirm = "确认",
	are_you_sure = "你确定要这么做？",
	yes = "是",
	cancel = "取消",
	reset_everything = "重置一切",
	reset_everything_tooltip = "警告：这将删除所有的白名单数据和列表！",
	go = "前往",
	customcheck_team = "这个职业有一个customCheck。这会覆盖bWhitelist的行为。\n\n请把文件中的\"customCheck\"改为\"bWhitelist_customCheck\"\n来让你的自定义代码和bWhitelist通用。",
	removed_from_whitelist = "你被移出\"%s\"的白名单了。",
	added_to_whitelist = "你被加入了\"%s\"的白名单了。",
	disable_all_whitelists = "禁用所有白名单",
	enable_all_whitelists = "启用所有白名单",
	player_left = "这个玩家下线了。",
	no_actions_available = "没有任何对这个玩家的行动。",
	remove_from_all_whitelists = "从所有白名单中移除",
	add_to_all_whitelists = "加入所有白名单",
	clear_unknown_jobs = "清理未知职业",
	clear_unknown_jobs_tooltip = "如果数据库中有一个不存在的职业，这个功能会将其剔除。职业的白名单数据将保留，以备后续使用。",
}
