--[[ 
	bWhitelist Croatian.

	Contributors: 
	Kyousei		-	STEAM_0:0:119269509
]]--

bWhitelist.Language = {
	permission_failure = "Vi trenutačno nemate dozvolu da uradite ovo.",
	disabled_whitelist = "Whitelist-a za ovaj posao je onemogućena.",
	no_whitelist_permission = "Vi nemate dozvolu da uredite ovu whitelist-u.",
	search_jobs = "Traži poslove...",
	steamid_finder = "SteamID Nalazač",
	type = "Tip",
	value = "Vrijednost",
	team_name = "Ime",
	select_job = "Odaberite posao na lijevo...",
	enable_whitelist = "Omoguči Whitelist-u?",
	enabling_whitelist = "Omogučivanje Whitelist-e...",
	add_to_whitelist = "Dodaj u Whitelist-u.",
	disable_whitelist = "Onemoguči Whitelist-u.",
	clear_whitelist = "Očisti Whitelist-u.",
	search = "Traži...",
	no_data = "Nema podataka!",
	retrieving = "Preuzimanje...",
	admin_mode = "Admin Moda",
	admin_tab = "Admin",
	jobs_tab = "Poslovi",
	players_tab = "Igrači",
	default_team = "Ovo je zadani tim. Nemožete Whitelist-ati zadani tim.",
	remove_from_whitelist = "Ukloni s Whitelist-e",
	player_name = "Ime",
	remove_from_whitelist_selected_tooltip = "Ukloni odabranog korsnika s Whitelist-e",
	add_to_whitelist_selected_tooltip = "Dodaj odabranog korisnika u Whitelist-u",
	clear_whitelist_tooltip = "[Samo Admin] čisti Whitelist-u. Svi SteamID-ovi i korisničke grupe su uklonjene.",
	disable_whitelist_tooltip = "Onemogučava Whitelist-u. Igrači se slobodno mogu pridružiti poslu.",
	add_to_whitelist_tooltip = "Dodaje StamID, SteamID64 ili korisničku grupu na Whitelist-u za ovaj posao.",
	remove_from_whitelist_tooltip = "Uklanja odabrani SteamID, SteamID64 ili korisničku grupu s Whitelist-e za ovaj posao.",
	in_jobs_file_tooltip = "Nemožete onemogučiti ovu Whitelist-u, zato što je bWhitelist omogućeno u vašoj DarkRP datoteci sa poslovima.",
	add_steamid = "Dodaj SteamID/64",
	add_usergroup = "Dodaj korisničku grupu",
	add_usergroup_modal = "Upišite korisničku grupu koju želite dodati u nastavku.",
	add_steamid_modal = "Zalijepite SteamID-SteamID64 koji želite dodati u nastavku.\nMolim vas da zapamtite da ima lakši način ya to, idite u \"Player\" tablicu u izborniku!",
	error = "Greška",
	not_a_steamid_or_64 = "To nije SteamID ili SteamID64!",
	already_exists = "To već postoji u Whitelist-i!",
	doesnt_exist = "To ne postoji u Whitelist-i!",
	copy = "Kopiraj",
	copy_tooltip = "Kopira odabranu korisničku grupu ili SteamID",
	player_left = "Oprostite, izgleda da je igrač napustio server.",
	no_enabled_whitelists = "Nema omogućenih Whitelist-a kojima imate pristup!",
	import_from_mayoz = "Uvezi iz Mayoz-ovog Whitelist sistema",
	import_from_nordahl = "Uvezi iz Nordahl-ovog Whitelist sistema",
	import_from_old_bwhitelist = "Uvezi is stare bWhitelist-e",
	view = "Pogledaj",
	no_import = "Izgleda da mi nismo mogli naći datoteke/datoteke su oštećene koje su potrebne za uvoz.",
	import_from_old_bwhitelist_tooltip = "Ako li možemo pronaći bilo koju datoteku od starog bWhitelist-a na vašem serveru, mi ćemo ih pretvoriti u nove datoteke.",
	import_from_mayoz_tooltip = "Ako li možemo pronaći bilo koju datoteku iz Mayoz-ovog Whitelist sistema na vašem serveru, mi ćemo ih pretvoriti u nove datoteke.",
	import_from_nordahl_tooltip = "Ako li možemo pronaći bilo koju datoteku iz Nordahl-ovog Whitelist sistema na vašem serveru, mi ćemo ih pretvoriti u nove datoteke.",
	disable_all_whitelists = "Svi poslovi će imati nhijovu Whitelist-u onemogućenu. Svi podatci će ostati.",
	enable_all_whitelists = "Svi poslovi će imati njihovu Whitelist-u omogućenu.",
	steamprofile = "Steam Profil",
	confirm = "Potvrdi",
	are_you_sure = "Jeste li sigurni da želite napraviti ovo?",
	yes = "Da",
	cancel = "Otkaži",
	reset_everything = "Poništi sve",
	reset_everything_tooltip = "UPOZORENJE: Ovo će izbrisati SVE Whitelist datoteke i omogućene Whitelist-e.",
	go = "Idi",
	customcheck_team = "Ovaj tim ima customCheck na sebi. Ovo nadjačava bWhitelist.\n\nMolimo promijenite \"customCheck\" u \"bWhitelist_customCheck\"\nu vašoj datoteci sa poslovima da bih vaš customCheck radio sa bWhitelist.",
	removed_from_whitelist = "Uklonjeni ste s Whitelist-e za \"%s\"",
	added_to_whitelist = "Dodani ste u Whitelist-u za \"%s\"",
	disable_all_whitelists = "Onemoguči sve Whitelist-e.",
	enable_all_whitelists = "Omoguči sve Whitelist-e.",
	player_left = "Igrač je otišao.",
	no_actions_available = "Nema akcija dostupnih za ovog igrača.",
	remove_from_all_whitelists = "Ukloni sa svih Whitelist-a",
	add_to_all_whitelists = "Dodaj u sve Whitelist-e",
	clear_unknown_jobs = "Očisti Nepoznate Poslove",
	clear_unknown_jobs_tooltip = "Ako ima Whitelist datoteka u bazi podataka povezana sa poslom koji ne postoji više, sve će biti uklonjeno sa ovim gumbom. Whitelist datoteke od tog posla će biti držano u slušaju da vam je potrebno u budučnosti.",
}
