--[[

	BWhitelist French

	Contributors:

	Shendow - STEAM_0:1:8039869

]]

BWhitelist.Language = {
	permission_failure = "Vous n'avez pas la permission de faire cela.",
	disabled_whitelist = "La whitelist pour ce job est désactivée.",
	no_whitelist_permission = "Vous n'avez pas la permission d'éditer cette whitelist.",
	search_jobs = "Chercher des jobs..",
	steamid_finder = "Chercheur de SteamID",
	type = "Type",
	value = "Valeur",
	team_name = "Nom",
	select_job = "Sélectionnez un métier sur la gauche..",
	enable_whitelist = "Activer la whitelist?",
	enabling_whitelist = "Activation de la whitelist..",
	add_to_whitelist = "Ajouter à la whitelist",
	disable_whitelist = "Désactiver la whitelist",
	clear_whitelist = "Vider la whitelist",
	search = "Chercher..",
	no_data = "Pas de données!",
	retrieving = "Chargement..",
	admin_mode = "Mode administration",
	admin_tab = "Administration",
	jobs_tab = "Métiers",
	players_tab = "Joueurs",
	default_team = "C'est l'équipe par défaut. Vous ne pouvez pas\nmettre de whitelist sur l'équipe par défaut.",
	remove_from_whitelist = "Enlever de la whitelist",
	player_name = "Nom",
	remove_from_whitelist_selected_tooltip = "Enlever l'utilisateur sélectionné d'une whitelist",
	add_to_whitelist_selected_tooltip = "Ajouter l'utilisateur sélectionné à une whitelist",
	clear_whitelist_tooltip = "[Admin seulement] Vide la whitelist. Tous les SteamIDs et groupes d'utilisateurs seront supprimés.",
	disable_whitelist_tooltip = "Désactiver la whitelist. Les joueurs pourront avoir ce job sans restriction.",
	add_to_whitelist_tooltip = "Ajouter un SteamID, SteamID64 ou groupe d'utilisateur à la whitelist pour ce job.",
	remove_from_whitelist_tooltip = "Enlever le SteamID, SteamID64 ou groupe d'utilisateur de la whitelist pour ce job.",
	in_jobs_file_tooltip = "Vous ne pouvez pas désactiver cette whitelist car BWhitelist est activé dans votre fichier de jobs.",
	add_steamid = "Ajouter un SteamID/64",
	add_usergroup = "Ajouter un groupe utilisateur",
	add_usergroup_modal = "Entrez le groupe utilisateur que vous voulez ajouter ci-dessous.",
	add_steamid_modal = "Collez le SteamID/SteamID64 que vous voulez ajouter ci-dessous.\nSouvenez-vous qu'il y a un moyen plus facile de faire cela; allez à l'onglet \"Joueurs\" dans le menu!",
	error = "Erreur",
	not_a_steamid_or_64 = "Ce n'est ni un SteamID ni un SteamID64!",
	already_exists = "Ceci existe déjà dans la whitelist!",
	doesnt_exist = "Ceci n'existe pas dans la whitelist!",
	copy = "Copier",
	copy_tooltip = "Copie le groupe utilisateur ou SteamID sélectionné.",
	player_left = "Désolé, on dirait que ce joueur a quitté le serveur.",
	no_enabled_whitelists = "Il n'y a aucune whitelist d'activée qui soit accessible!",
	import_from_mayoz = "Importer de Mayoz's Whitelisting System",
	import_from_nordahl = "Importer de Nordahl's Whitelisting System",
	import_from_old_bwhitelist = "Importer de l'ancien BWhitelist",
	view = "Voir",
	no_import = "On dirait qu'on n'a pas peu trouver les fichiers/les fichiers sont corrompus pour l'importation.",
	import_from_old_bwhitelist_tooltip = "Si nous pouvons trouver des fichiers de l'ancien BWhitelist, ils seront convertis à la nouvelle version.",
	import_from_mayoz_tooltip = "Si nous pouvons trouver des fichiers de Mayoz's Whitelisting System sur votre serveur, ils seront convertis en fichiers BWhitelist.",
	import_from_nordahl_tooltip = "Si nous pouvons trouver des fichiers de Nordahl's Whitelisting System sur votre serveur, ils seront convertis en fichiers BWhitelist.",
	disable_all_whitelists = "Les listes blanches de tous les jobs seront désactivées. Aucune donnée ne sera supprimée.",
	enable_all_whitelists = "Les listes blanches de tous les jobs seront activées.",
	steamprofile = "Profil Steam",
	confirm = "Confirmer",
	are_you_sure = "Voulez-vous vraiment effectuer cette action?",
	yes = "Oui",
	cancel = "Annuler",
	reset_everything = "Tout remettre à zéro",
	reset_everything_tooltip = "ATTENTION : Ceci supprimera TOUTES les données de whitelist.",
	go = "Aller",
	notify_customcheck = "Ce job a un customCheck qui a outrepassé BWhitelist et vous empêche de l'avoir.",
	customcheck_team = "Cette équipe a un customCheck. Ceci outrepasse BWhitelist.\n\nVeuillez changer \"customCheck\" à \"BWhitelist_customCheck\"\ndans votre fichier de jobs pour que customCheck fonctionne avec BWhitelist.",
	removed_from_whitelist = "Vous avez été enlevé de la whitelist pour \"%s\"",
	added_to_whitelist = "Vous avez été ajouté à la whitelist pour \"%s\"",
	disable_all_whitelists = "Désactiver tous les whitelists",
	enable_all_whitelists = "Activer tous les whitelists",
	player_left = "Le joueur s'est déconnecté.",
	no_actions_available = "Pas d'actions disponibles pour ce joueur.",
}
