--[[
	BWhitelist German
	
	Contributors:
	
	FearBomber - 76561198050514903
]]

bLogs.Language = {
	permission_failure = "Du hast momentan nicht die Befugnis um dies zu tun.",
	disabled_whitelist = "Die Whitelist für diesen Job ist deaktiviert.",
	no_whitelist_permission = "Du hast nicht die Berechtigung die Whitelist zu bearbeiten.",
	search_jobs = "Suche Berufe...",
	steamid_finder = "SteamID Finder",
	type = "Typ",
	value = "Wert",
	team_name = "Name",
	select_job = "Wähle links einen Beruf...",
	enable_whitelist = "Whitelist aktivieren?",
	enabling_whitelist = "Aktiviere Whitelist...",
	add_to_whitelist = "Zur Whitelist zufügen",
	disable_whitelist = "Whitelist deaktivieren",
	clear_whitelist = "Whitelist löschen",
	search = "Suche...",
	no_data = "Keine Einträge!",
	retrieving = "Frage ab...",
	admin_mode = "Admin Modus",
	admin_tab = "Admin",
	jobs_tab = "Berufe",
	players_tab = "Spieler",
	default_team = "Dies ist das Standard Team. Du kannst das Standard Team nicht zur Whitelist zufügen.",
	remove_from_whitelist = "Von der Whitelist entfernen",
	player_name = "Name",
	remove_from_whitelist_selected_tooltip = "Entferne den ausgewählten Spieler von der Whitelist",
	add_to_whitelist_selected_tooltip = "Füge den ausgewählten Spieler zu der Whitelist hinzu",
	clear_whitelist_tooltip = "[Nur für Admins] Whitelist geleert. Alle SteamIDs und Benutzergruppen wurden gelöscht.",
	disable_whitelist_tooltip = "Deaktiviere die Whitelist. Spieler können diesen Job kostenlos wählen.",
	add_to_whitelist_tooltip = "Fügt die SteamID, SteamID64 oder Benutzergruppe zur Whitelist für diesen Beruf hinzu.",
	remove_from_whitelist_tooltip = "Entfernt die SteamID, SteamID64 oder Benutzergruppe von der Whitelist für diesen Beruf.",
	in_jobs_file_tooltip = "Du kannst diese Whitelist nicht deaktivieren weil BWhitelist in deinen DarkRP Berufen aktiviert ist.",
	add_steamid = "Füge SteamID/64 hinzu",
	add_usergroup = "Füge Benutzergruppe hinzu",
	add_usergroup_modal = "Wähle die Benutzergruppe die du unten zufügen willst.",
	add_steamid_modal = "Füge die SteamID/SteamID64 ein die du unten zufügen willst.\nDenk dran das es einen einfacheren Weg gibt dies zu tun, öffne den \"Player\" tab im menu!",
	error = "Fehler",
	not_a_steamid_or_64 = "Das ist keine SteamID oder SteamID64!",
	already_exists = "Das existiert bereits in der Whitelist!",
	doesnt_exist = "Das existiert nicht in der Whitelist!",
	copy = "Kopieren",
	copy_tooltip = "Kopiert die ausgewählte Benutzergruppe oder SteamID.",
	player_left = "Sorry, sieht so aus als wenn der / die Spieler den Server verlassen haben.",
	no_enabled_whitelists = "Es gibt keine aktivierte Whitelists zu der du Zugriff hast!",
	import_from_mayoz = "Importiere von Mayoz's Whitelisting System",
	import_from_nordahl = "Importiere from Nordahl's Whitelisting System",
	import_from_old_bwhitelist = "Importiere from old BWhitelist",
	view = "Ansehen",
	no_import = "Es sieht so aus als ob wir die Datei nicht finden konnten/die erforderlichen Datein die zu importieren sind, sind beschädigt.",
	import_from_old_bwhitelist_tooltip = "Wenn wir alte BWhitelist Daten auf dem Server finden, übertragen wir sie in die neuen Daten.",
	import_from_mayoz_tooltip = "Wenn wir alte Mayoz's Whitelisting System's Daten auf dem Server finden, übertragen wir sie in die neuen BWhitelist Daten.",
	import_from_nordahl_tooltip = "Wenn wir alte Nordahl's Whitelisting System's Daten auf dem Server finden, übertragen wir sie in die neuen BWhitelist Daten.",
	disable_all_whitelists = "Alle Berufe werden ihre Whitelist deaktiviert bekommen. Alle Daten bleiben vorhanden.",
	enable_all_whitelists = "Alle Berufe werden ihre Whitelist aktiviert bekommen.",
	steamprofile = "Steam Profil",
	confirm = "Bestätigen",
	are_you_sure = "Bist du sicher das du diese Aktion ausführen willst?",
	yes = "Ja",
	cancel = "Abbrechen",
	reset_everything = "Alles zurücksetzen",
	reset_everything_tooltip = "ACHTUNG: Dies wird die GESAMMTE Whitelist Datei und aktivierte Whitelist löschen.",
	go = "Suchen",
	notify_customcheck = "Der Beruf den du versucht hattest zu wählen hat eine customCheck welche die BWhitelist überschreibt und dich vom Beitritt abhält.",
	customcheck_team = "Das Team hat eine customCheck. Diese überschreibt die BWhitelist.\n\nBitte änder die  \"customCheck\" to \"BWhitelist_customCheck\"\nin deinen Berufs Datein um deine customCheck für BWhitelist freizugeben.",
	removed_from_whitelist = "Du wurdest von der Whitelist für \"%s\" entfernt",
	added_to_whitelist = "Du wurdest für \"%s\" zur Whitelist zugefügt",
	disable_all_whitelists = "Alle Whitelists deaktivieren",
	enable_all_whitelists = "Alle Whitelists aktivieren",
	player_left = "Der Spieler hat verlassen.",
	no_actions_available = "Es sind keine Aktionen für den Spieler verfügbar.",
}
