--[[

	bWhitelist Polish
	
	Contributors:
	
	Geniush - STEAM_0:1:86426511
	
]]

bWhitelist.Language = {
	permission_failure = "Nie masz uprawnień żeby to zrobić!",
	disabled_whitelist = "Whitelista do tej pracy jest wyłączona.",
	no_whitelist_permission = "Nie masz uprawnień żeby edytować tą whitelistę.",
	search_jobs = "Szukaj prac...",
	steamid_finder = "wyszukiwarka SteamID",
	type = "Typ",
	value = "Wartość",
	team_name = "Nazwa",
	select_job = "Wybierz pracę po lewej...",
	enable_whitelist = "Włączyć Whitelistę?",
	enabling_whitelist = "Włączanie Whitelisty...",
	add_to_whitelist = "Dodaj do Whitelisty",
	disable_whitelist = "Wyłącz Whitelistę",
	clear_whitelist = "Wyczyść Whitelistę",
	search = "Szukaj...",
	no_data = "Brak danych!",
	retrieving = "Pobieranie...",
	admin_mode = "Tryb Admina",
	admin_tab = "Admin",
	jobs_tab = "Prace - Jobs",
	players_tab = "Gracze",
	default_team = "To jest domyślna praca. Nie możesz dodać do whitelisty domyślnych prac.",
	remove_from_whitelist = "Usuń z Whitelisty",
	player_name = "Nazwa",
	remove_from_whitelist_selected_tooltip = "Usuń wybranego użytkownika z whitelisty",
	add_to_whitelist_selected_tooltip = "Dodaj wybranego użytkownika do whitelisty",
	clear_whitelist_tooltip = "[Tylko Admin] Wyczyść całą whitelistę. Wszystkie SteamID i grupy zostaną usunięte.",
	disable_whitelist_tooltip = "Wyłącz whitelistę. Gracze mogą wybrać dowolną pracę.",
	add_to_whitelist_tooltip = "Dodaje SteamID, SteamID64 albo grupę do whitelisty dla tej pracy.",
	remove_from_whitelist_tooltip = "Usuwa SteamID, SteamID64 albo grupę do whitelisty dla tej pracy.",
	in_jobs_file_tooltip = "Nie możesz wyłączyć tej whitelisty, ponieważ bWhitelist jest włączony w plikach prac DarkRP.",
	add_steamid = "Dodaj SteamID/64",
	add_usergroup = "Dodaj Grupę",
	add_usergroup_modal = "Wpisz grupę, którą chcesz dodać.",
	add_steamid_modal = "Wklej poniżej SteamID/SteamID64 które chcesz dodać.\nPamiętaj jest łatwiejszy sposób -  karta \"Player\" w menu!",
	error = "Error",
	not_a_steamid_or_64 = "To nie jest SteamID lub SteamID64!",
	already_exists = "To już istnieje w whitelist!",
	doesnt_exist = "To nie istnieje w whitelist!",
	copy = "Kopiuj",
	copy_tooltip = "Kopiuje wybraną grupę albo SteamID.",
	player_left = "Przepraszam, wygląda na to, że gracz opuścił serwer.",
	no_enabled_whitelists = "Nie ma włączonej whitelisty do której masz dostęp!",
	import_from_mayoz = "Importuj z Mayoz's Whitelisting System",
	import_from_nordahl = "Importuj z Nordahl's Whitelisting System",
	import_from_old_bwhitelist = "Importuj z starej wersji bWhitelist",
	view = "Zobacz",
	no_import = "Nie znaleziono pliku/plików wymaganych do importu.",
	import_from_old_bwhitelist_tooltip = "Jeśli znajdziemy pliki z starej wersji bWhitelist, przekonwertujemy je na nowe.",
	import_from_mayoz_tooltip = "Jeśli znajdziemy pliki z Mayoz's Whitelisting System's, przekonwertujemy je na bWhitelist.",
	import_from_nordahl_tooltip = "Jeśli znajdziemy pliki z Nordahl's Whitelisting System's files on your server, przekonwertujemy je na bWhitelist.",
	disable_all_whitelists = "Wszystkie prace mają wyłączoną whitelistę. Wszystkie dane zostaną na dysku.",
	enable_all_whitelists = "Wszystkie prace mają włączoną whitelistę.",
	steamprofile = "Profil Steam",
	confirm = "Potwierdź",
	are_you_sure = "Jesteś pewien, że chcesz to zrobić?",
	yes = "Tak",
	cancel = "Anuluj",
	reset_everything = "Resetuj wszystko",
	reset_everything_tooltip = "UWAGA: Zostaną usunięte wszystkie dane i whitelisty!",
	go = "Kontynuuj",
	customcheck_team = "Ta praca ma włączony customCheck. Powoduje to nadpisanie bWhitelist.\n\nProszę zmienić \"customCheck\" na \"bWhitelist_customCheck\"\nw plikach prac żeby customCheck działał z bWhitelist.",
	removed_from_whitelist = "Zostałeś usunięty z whitelisty przez \"%s\"",
	added_to_whitelist = "Zostałeś dodany do whitelisty przez \"%s\"",
	disable_all_whitelists = "Wyłącz wszystkie whitelisty",
	enable_all_whitelists = "Włącz wszystkie whitelisty",
	player_left = "Gracz opuścił serwer.",
	no_actions_available = "Brak dostępnych działań dla tego gracza.",
	remove_from_all_whitelists = "Usuń ze wszystkich whitelist",
	add_to_all_whitelists = "Dodaj do wszystkich whitelist",
	clear_unknown_jobs = "Wyczyść nieznane prace",
	clear_unknown_jobs_tooltip = "Jeśli w bazie danych istnieją dane whitelisty odnoszące się do nieistniejącej pracy zostaną usunięte tym przyciskiem. Pozostałe pliki zostaną zachowane w przypadku gdybyś ich w przyszłości potrzebował.",
}
