--[[

	BWhitelist Portuguese
  
	Contributors:
  
	Pedro - STEAM_0:0:150648784
  
]]

BWhitelist.Language = {
	permission_failure = "You don't currently have permission to do this.",
	disabled_whitelist = "The whitelist for this job is disabled.",
	no_whitelist_permission = "You don't have permission to edit this whitelist.",
	search_jobs = "Search jobs...",
	steamid_finder = "SteamID Finder",
	type = "Type",
	value = "Value",
	team_name = "Name",
	select_job = "Select a job on the left...",
	enable_whitelist = "Enable Whitelist?",
	enabling_whitelist = "Enabling Whitelist...",
	add_to_whitelist = "Add to Whitelist",
	disable_whitelist = "Disable Whitelist",
	clear_whitelist = "Clear Whitelist",
	search = "Search...",
	no_data = "No data!",
	retrieving = "Retrieving...",
	admin_mode = "Admin Mode",
	admin_tab = "Admin",
	jobs_tab = "Jobs",
	players_tab = "Players",
	default_team = "This is the default team. You cannot whitelist the default team.",
	remove_from_whitelist = "Remove from Whitelist",
	player_name = "Name",
	remove_from_whitelist_selected_tooltip = "Remove the selected user from a whitelist",
	add_to_whitelist_selected_tooltip = "Add the selected user to a whitelist",
	clear_whitelist_tooltip = "[Admin only] Clears the whitelist. All SteamIDs and usergroups are removed.",
	disable_whitelist_tooltip = "Disables the whitelist. Players can join the job freely.",
	add_to_whitelist_tooltip = "Adds a SteamID, SteamID64 or usergroup to the whitelist for this job.",
	remove_from_whitelist_tooltip = "Removes the selected SteamID, SteamID64 or usergroup from the whitelist for this job.",
	in_jobs_file_tooltip = "You can't disable this whitelist because it is BWhitelist enabled in your DarkRP jobs file.",
	add_steamid = "Add SteamID/64",
	add_usergroup = "Add Usergroup",
	add_usergroup_modal = "Type the usergroup you want to add below.",
	add_steamid_modal = "Paste the SteamID/SteamID64 you want to add below.\nPlease remember that there is an easier way to do this, go to the \"Player\" tab in the menu!",
	error = "Error",
	not_a_steamid_or_64 = "That's not a SteamID or SteamID64!",
	already_exists = "That already exists in the whitelist!",
	doesnt_exist = "That doesn't exist in the whitelist!",
	copy = "Copy",
	copy_tooltip = "Copies the selected usergroup or SteamID.",
	player_left = "Sorry, it looks like that player's left the server.",
	no_enabled_whitelists = "There's no enabled whitelists that you have access to!",
	import_from_mayoz = "Import from Mayoz's Whitelisting System",
	import_from_nordahl = "Import from Nordahl's Whitelisting System",
	import_from_old_bwhitelist = "Import from old BWhitelist",
	view = "View",
	no_import = "It looks like we couldn't find the files/the files are corrupted that are required to import.",
	import_from_old_bwhitelist_tooltip = "If we can find any of the old BWhitelist files on your server, we'll convert them into the new files.",
	import_from_mayoz_tooltip = "If we can find any of Mayoz's Whitelisting System's files on your server, we'll convert them into BWhitelist files.",
	import_from_nordahl_tooltip = "If we can find any of Nordahl's Whitelisting System's files on your server, we'll convert them into BWhitelist files.",
	disable_all_whitelists = "All jobs will have their whitelists disabled. All data will stay.",
	enable_all_whitelists = "All jobs will have their whitelists enabled.",
	steamprofile = "Steam Profile",
	confirm = "Confirm",
	are_you_sure = "Are you sure you want to do this?",
	yes = "Yes",
	cancel = "Cancel",
	reset_everything = "Reset everything",
	reset_everything_tooltip = "WARNING: This will delete ALL whitelist data and enabled whitelists.",
	go = "Go",
	customcheck_team = "This team has a customCheck on it. This overrides BWhitelist.\n\nPlease change \"customCheck\" to \"BWhitelist_customCheck\"\nin your jobs file for your customCheck to work with BWhitelist.",
	removed_from_whitelist = "You were removed from the whitelist for \"%s\"",
	added_to_whitelist = "You were added to the whitelist for \"%s\"",
	disable_all_whitelists = "Disable all whitelists",
	enable_all_whitelists = "Enable all whitelists",
	player_left = "The player has left.",
	no_actions_available = "No actions available for this player.",
	remove_from_all_whitelists = "Remove from all whitelists",
	add_to_all_whitelists = "Add to all whitelists",
	clear_unknown_jobs = "Clear Unknown Jobs",
	clear_unknown_jobs_tooltip = "If there is whitelist data in the database related to a job that doesn't exist anymore, it will all be deleted with this button. The whitelist data of that job will be kept in case you need it in future.",
}
