--[[

	BWhitelist Russian

	Contributors:
	WhippaSnappers STEAM_1:1:82756840

]]

BWhitelist.Language = {
	permission_failure = "Отказано в доступе.",
	disabled_whitelist = "Для этой профессии whitelist отключен.",
	no_whitelist_permission = "Нет прав для редактирования этого whitelist'а.",
	search_jobs = "Поиск профессии...",
	steamid_finder = "Поисковик SteamID",
	type = "Тип",
	value = "Значение",
	team_name = "Имя",
	select_job = "Выберите профессию слева...",
	enable_whitelist = "Включить whitelist?",
	enabling_whitelist = "Включаю whitelist...",
	add_to_whitelist = "Добавить в whitelist",
	disable_whitelist = "Отключить whitelist",
	clear_whitelist = "Очистить whitelist",
	search = "Поиск...",
	no_data = "Нет данных!",
	retrieving = "Получаю...",
	admin_mode = "Админ режим",
	admin_tab = "Админ",
	jobs_tab = "Профессии",
	players_tab = "Игроки",
	default_team = "Это дефолтная тима. Вы не можете установить whitelist для нее.",
	remove_from_whitelist = "Удалить из whitelist'а",
	player_name = "Имя",
	remove_from_whitelist_selected_tooltip = "Удалить этого игрока из whitelist'а",
	add_to_whitelist_selected_tooltip = "Добавить этого игрока в whitelist",
	clear_whitelist_tooltip = "[Только админам] Очищает whitelist. Все SteamID и юзергруппы будут удалены.",
	disable_whitelist_tooltip = "Отключает whitelist. Игроки смогут устраиваться на любую профессию.",
	add_to_whitelist_tooltip = "Добавляет SteamID, SteamID64 или юзергруппу в whitelist для этой профессии.",
	remove_from_whitelist_tooltip = "Удаляет выбранный(ую) SteamID, SteamID64 или юзергруппу из whitelist'а для этой профессии.",
	in_jobs_file_tooltip = "Вы не можете отключить этот whitelist так, как он активирован в конфиге профессий вашего DarkRP.",
	add_steamid = "Добавить SteamID/64",
	add_usergroup = "Добавить юзергруппу",
	add_usergroup_modal = "Напишите юзергруппу, которую хотите добавить, ниже.",
	add_steamid_modal = "Вставьте SteamID/SteamID64, который вы хотите добавить в whitelist.\nК стати, есть более простой способ сделать это, проверьте вкладку\"Player\" в меню!",
	error = "Ошибка",
	not_a_steamid_or_64 = "Это не SteamID и не SteamID64!",
	already_exists = "Это уже есть в whitelist'е!",
	doesnt_exist = "Этого еще нет в whitelist'е!",
	copy = "Скопировать",
	copy_tooltip = "Копирует выбранную юзергруппу или SteamID.",
	player_left = "Упс! Похоже, игрок покинул сервер.",
	no_enabled_whitelists = "Не могу найти активных whitelist'ов, к которым  у вас есть доступ!",
	import_from_mayoz = "Импорт из whitelist'а от Mayoz'а",
	import_from_nordahl = "Импорт из whitelist'а от Nordahl'а",
	import_from_old_bwhitelist = "Импорт из старого BWhitelist",
	view = "Просмотреть",
	no_import = "Похоже, мы не смогли найти Файлы/возможно, они повреждены.",
	import_from_old_bwhitelist_tooltip = "Если мы найдем файлы от старого BWhitelist на сервере, то конвертируем их для новой версии.",
	import_from_mayoz_tooltip = "Если мы найдем файлы whitelist'а от Mayoz'а, то конвертируем их для BWhitelist.",
	import_from_nordahl_tooltip = "Если мы найдем файлы whitelist'а от Nordahl'а, то конвертируем их для BWhitelist.",
	disable_all_whitelists = "Whitelist'ы всех профессий будут отключены. Все данные останутся.",
	enable_all_whitelists = "Вайт листы всех профессий будут включены.",
	steamprofile = "Steam профиль",
	confirm = "Подтвердить",
	are_you_sure = "Вы действительно хотите удалить это?",
	yes = "Да",
	cancel = "Отменить",
	reset_everything = "Сбросить все",
	reset_everything_tooltip = "ОПАНЬКИ: Это удалить все whitelist'ы и их настройки.",
	go = "Вперед",
	customcheck_team = "Эта тима имеет customCheck. Это блокирует работу BWhitelist.\n\nПожалуйста, измените \"customCheck\" на \"BWhitelist_customCheck\"\nв файле ваших профессий, чтобы customCheck работал с BWhitelist.",
	removed_from_whitelist = "Вы были удалены из whitelist'а \"%s\"",
	added_to_whitelist = "Вы были добавлены в whitelist'а \"%s\"",
	disable_all_whitelists = "Отключить все whitelist'ы",
	enable_all_whitelists = "Включить все whitelist'ы",
	player_left = "Игрок вышел.",
	no_actions_available = "Нет доступных действий для этого игрока.",
	remove_from_all_whitelists = "Удалить из всех whitelist'ов",
	add_to_all_whitelists = "Добавить во все whitelist'ы",
	clear_unknown_jobs = "Удалить неизвестные профессии",
	clear_unknown_jobs_tooltip = "Если в базе данных есть записи, относящиеся к более несуществующей профессии, они будут удалены по нажатию этой кнопки. Информация в whitelist'е об этой профессии будет сохранена, для возможности ее использования в будущем.",
}
