--[[

	bWhitelist Turkish
	
	Contributors:
	
	heriporter22 - STEAM_1:0:74235490
	
]]

bWhitelist.Language = {
	permission_failure = "Şu Anda Bunu Düzenleme İznin Yok.",
	disabled_whitelist = "whitelist Bu Meslek İçin Kapatılmış.",
	no_whitelist_permission = "whitelist'i Düzenleme İznin Yok!",
	search_jobs = "Meslek Ara...",
	steamid_finder = "SteamID Bulucu",
	type = "Tip",
	value = "Miktar",
	team_name = "Ad",
	select_job = "Soldan Meslek Seçin...",
	enable_whitelist = "Whitelist'i Açmak İstediğine Emin Misin?",
	enabling_whitelist = "Whitelist Açılıyor...",
	add_to_whitelist = "Whitelist'e Ekle",
	disable_whitelist = "Whitelist'i Kapat",
	clear_whitelist = "Whitelist'i Temizle",
	search = "Ara...",
	no_data = "Bilgi Yok!",
	retrieving = "Alınıyor...",
	admin_mode = "Yetkili Modu",
	admin_tab = "Yetkili",
	jobs_tab = "Meslekler",
	players_tab = "Oyuncular",
	default_team = "Ana Takımı Seçtiniz. Ana Takımı whitelist'e Ekleyemezsin.",
	remove_from_whitelist = "Whitelist'den Çıkar",
	player_name = "Ad",
	remove_from_whitelist_selected_tooltip = "Seçili Oyuncuyu whitelist'den Çıkar",
	add_to_whitelist_selected_tooltip = "Seçili Oyuncuyu whitelist'e Ekle",
	clear_whitelist_tooltip = "[Sadece Yetkili] whitelist'i Temizle. Tüm SteamID'ler Ve Kullanıcı Grupları Kaldırılır.",
	disable_whitelist_tooltip = "whitelist'i Kapatır. Oyuncular İstedikleri Mesleğe Girebilirler.",
	add_to_whitelist_tooltip = "Bu Meslek İçin whitelist'e SteamID, SteamID64 Ya Da Kullanıcı Grubu Ekle.",
	remove_from_whitelist_tooltip = "Seçili SteamID, SteamID64 Ya Da Kullanıcı Grubunun whitelist'den Çıkarır.",
	in_jobs_file_tooltip = "whitelist'i Kapatamazsın. Çünkü bWhitelist Darkrp Meslek Dosyalarında Aktif Edilmiş.",
	add_steamid = "SteamID/64 Ekle",
	add_usergroup = "Kullanıcı Grubu Ekle",
	add_usergroup_modal = "Eklemek İstediğiniz Kullanıcı Grubunu Yazın.",
	add_steamid_modal = "Eklemek İstediğiniz SteamID/SteamID64'yi Yazın\nUnutmayın ki Bunu Yapmanın En Kolay Yolu, Menüdeki "Oyuncu" Sekmesine Gidin!",
	error = "Hata",
	not_a_steamid_or_64 = "Bu Bir SteamID/SteamID64 Değil!",
	already_exists = "whitelist'de Zaten Böyle Birşey Var!",
	doesnt_exist = "whitelist'de Böyle Birşey Yok!",
	copy = "Kopyala",
	copy_tooltip = "Seçili Kullanıcı Grubu Ya Da SteamID Kopyalar.",
	player_left = "Özür Dileriz, Oyuncu Sunucudan Çıkmışa Benziyor.",
	no_enabled_whitelists = "Senin Erişebileceğin Açık Bir whitelist Yok!",
	import_from_mayoz = "Mayoz's Whitelisting System'den Import'la",
	import_from_nordahl = "Nordahl's Whitelisting System'den Import'la",
	import_from_old_bwhitelist = " Eski bWhitelist'den Import'la",
	view = "Gör",
	no_import = "Görünen O ki Dosyaları Bulamadık/Importlayabilmek İçin Dosyaların Doğru Olmaıs Gerek.",
	import_from_old_bwhitelist_tooltip = "Sunucunuzda Eski bWhitelist Dosyalarını Bulursak, Onları Yeni Olarak Güncelleceyeceğiz.",
	import_from_mayoz_tooltip = "Sunucudunuzda Mayoz's Whitelisting System'in Dosyalarını Bulursak Onları, bWhitelist Dosyalarına Çevireceğiz.",
	import_from_nordahl_tooltip = "Sunucunuzda Nordahl's Whitelisting System'in Dosyalarını Bulursak Onları, bWhitelist Dosyalarına Çevireceğiz.",
	disable_all_whitelists = "Tüm Mesleklerde whitelists Kapatıldı. Bilgiler Saklanmaya Devam Edecek.",
	enable_all_whitelists = "Tüm Mesleklerin whitelist'i Açıldı.",
	steamprofile = "Steam Profili",
	confirm = "Onayla",
	are_you_sure = "Bunu Yapmak İstediğine Emin Misin?",
	yes = "Evet",
	cancel = "İptal",
	reset_everything = "Herşeyi Sıfırla",
	reset_everything_tooltip = "UYARI: Bu İşlem Tüm whitelist Bilgilerini Ve Aktif whitelist'leri Siler.",
	go = "Git",
	customcheck_team = "Bu Takım customCheck'e Sahip. Bu bWhitelist İle Çakışabilir.\n\nLütfen "customCheck" Bunu "bWhitelist_customCheck"\Olarak Deiştirin customCheck'in bWhitelist İle Doğru Çalışması İçin.",
	removed_from_whitelist = ""%s\ whitelist'den Kaldırdın",
	added_to_whitelist = ""%s\ whitelist'e Ekledin",
	disable_all_whitelists = "Tüm whitelist'leri Kapatır",
	enable_all_whitelists = "Tüm whitelist'leri Aktif Eder",
	player_left = "Oyuncu Çıktı.",
	no_actions_available = "Bu Oyuncu İçin Bir Eylem Yok.",
	remove_from_all_whitelists = "Tüm whitelist'leri Kaldır",
	add_to_all_whitelists = "Hepsini whitelist'e Ekle",
	clear_unknown_jobs = "Bilinmeyen Meslekleri Temizle",
	clear_unknown_jobs_tooltip = "whitelist'de Uyuşmayan Bir Meslek Var, Bu Butona Basarak Silebilirsiniz. whitelist Bu Bilgileri Gelecekte İşinize Yarar Diye Saklayacaktır.",
}
